Repository nasa/opera-sds-pcm, pull requests merged in 2023-10, with the labels that each got.

#638 Issue 633: Add trace element on CNM-S message
  cluster_provisioning/dev-common/override.tf
  cluster_provisioning/dev-e2e-event-misfire/main.tf
  cluster_provisioning/dev-e2e-event-misfire/variables.tf
  cluster_provisioning/dev-e2e-pge/main.tf
  cluster_provisioning/dev-e2e-pge/variables.tf
  cluster_provisioning/dev-e2e/main.tf
  cluster_provisioning/dev-e2e/variables.tf
  cluster_provisioning/dev-int/main.tf
  cluster_provisioning/dev-releaser/main.tf
  cluster_provisioning/dev-releaser/variables.tf
  cluster_provisioning/dev-restore-snapshot/main.tf
  cluster_provisioning/dev-restore-snapshot/variables.tf
  cluster_provisioning/dev/main.tf
  cluster_provisioning/dev/variables.tf
  cluster_provisioning/int/int-fwd/main.tf
  cluster_provisioning/int/int-fwd/override.tf
  cluster_provisioning/int/int-pop1/override.tf
  cluster_provisioning/int/int_override.tf
  cluster_provisioning/modules/common/mozart.tf
  cluster_provisioning/modules/common/variables.tf
  cluster_provisioning/ops/override.tf
  cluster_provisioning/pst/override.tf
  conf/sds/files/config-branch.xml
  conf/sds/files/config.xml
  conf/sds/files/docker-compose.yml.verdi
  conf/sds/files/test/import_product_delivery_rules.sh
  conf/sds/rules/user_rules-cnm.json.tmpl
  docker/Dockerfile
  docker/hysds-io.json.process_cnm_response
  docker/hysds-io.json.send_notify_msg
  docker/job-spec.json.process_cnm_response
  docker/job-spec.json.send_notify_msg
  tools/send_notify_msg.sh
Labels: pcm.r02

#637 Issue 634: move bach-api to metrics instance
  cluster_provisioning/modules/common/grq_factotum_metrics.tf
  cluster_provisioning/modules/common/mozart.tf
  conf/sds/cluster.py
  conf/sds/files/supervisord.conf.grq
  conf/sds/files/supervisord.conf.grq.aws_es
  conf/sds/files/supervisord.conf.metrics
  tools/ops/cmr_audit/cmr_client.py
Labels: pcm.r02

#640 R2 PGE v2.1.0 Integration
  cluster_provisioning/dev-e2e-event-misfire/variables.tf
  cluster_provisioning/dev-e2e-pge/variables.tf
  cluster_provisioning/dev-e2e/variables.tf
  cluster_provisioning/dev-int/override.tf
  cluster_provisioning/dev-restore-snapshot/variables.tf
  cluster_provisioning/dev/variables.tf
  cluster_provisioning/ebs-snapshot/variables.tf
  cluster_provisioning/modules/common/variables.tf
  conf/pge_outputs.yaml
  conf/sds/files/datasets.json
  conf/sds/files/datasets.json.tmpl.asg
  conf/settings.yaml
  docker/job-spec.json.SCIFLO_L2_CSLC_S1
  docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC
  docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC_hist
  docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist
  docker/job-spec.json.SCIFLO_L2_RTC_S1
  docker/job-spec.json.SCIFLO_L2_RTC_S1_STATIC
  opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1_STATIC.yaml
  opera_chimera/configs/pge_configs/PGE_L2_RTC_S1_STATIC.yaml
  opera_chimera/constants/opera_chimera_const.py
  opera_chimera/opera_pge_job_submitter.py
  tests/util/test_pge_util.py
  util/pge_util.py
  wrapper/opera_pge_wrapper.py
Labels: enhancement, pcm.r02

#641 Issue 630 geofilter
  conf/sds/rules/user_rules.json
  conf/settings.yaml
  data_subscriber/daac_data_subscriber.py
  data_subscriber/query.py
  docker/hysds-io.json.slcs1a_query
  docker/hysds-io.json.slcs1b_query
  docker/job-spec.json.slcs1a_query
  docker/job-spec.json.slcs1a_query_hist
  docker/job-spec.json.slcs1b_query
  docker/job-spec.json.slcs1b_query_hist
  geo/california_opera.geojson
  geo/geo_util.py
  geo/nevada_opera.geojson
  tests/data_subscriber/test_query.py
  tests/geo/test_geo_util.py
  tools/ops/README.md
Labels: pcm.r02

#647 Add missing import on cmr_audit_slc.py
  tools/ops/cmr_audit/cmr_audit_slc.py
Labels: bug

#635 DSWx-S1 ER4 Integration
  cluster_provisioning/dev-e2e-event-misfire/variables.tf
  cluster_provisioning/dev-e2e-pge/variables.tf
  cluster_provisioning/dev-e2e/variables.tf
  cluster_provisioning/dev-int/override.tf
  cluster_provisioning/dev-restore-snapshot/variables.tf
  cluster_provisioning/dev/variables.tf
  cluster_provisioning/ebs-snapshot/variables.tf
  cluster_provisioning/modules/common/launch_template_user_data.sh.tmpl
  cluster_provisioning/modules/common/variables.tf
  conf/RunConfig.yaml.L3_DSWx_S1.jinja2.tmpl
  conf/pge_outputs.yaml
  conf/schema/RunConfig_schema.L3_DSWx_S1.yaml
  conf/sds/files/datasets.json
  conf/sds/files/datasets.json.tmpl.asg
  conf/sds/rules/user_rules-cnm.json.tmpl
  conf/sds/rules/user_rules.json
  conf/settings.yaml
  docker/hysds-io.json.SCIFLO_L3_DSWx_S1
  docker/job-spec.json.SCIFLO_L3_DSWx_S1
  extractor/extract.py
  opera_chimera/accountability.py
  opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml
  opera_chimera/precondition_functions.py
  opera_chimera/wf_xml/L3_DSWx_S1.sf.xml
  product2dataset/product2dataset.py
  tests/util/test_pge_util.py
  util/pge_util.py
  wrapper/opera_pge_wrapper.py
  wrapper/pge_functions.py
Labels: enhancement, needs triage, pcm.r03
