Repository nasa/opera-sds-pcm, pull requests merged in 2023-05, with the labels that each got.

#501 R2 PGE 2.0.0 RC 1.3 Integration
  cluster_provisioning/dev-e2e-event-misfire/variables.tf
  cluster_provisioning/dev-e2e-pge/variables.tf
  cluster_provisioning/dev-e2e/variables.tf
  cluster_provisioning/dev-int/override.tf
  cluster_provisioning/dev-restore-snapshot/variables.tf
  cluster_provisioning/dev/variables.tf
  cluster_provisioning/ebs-snapshot/variables.tf
  cluster_provisioning/modules/common/variables.tf
  conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl
  conf/schema/RunConfig_schema.L2_CSLC_S1.yaml
  conf/settings.yaml
  data_subscriber/download.py
  docker/job-spec.json.SCIFLO_L2_CSLC_S1
  docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist
  docker/job-spec.json.SCIFLO_L2_RTC_S1
  tools/stage_orbit_file.py
Labels: bug, needs triage, pcm.r02

#504 Issue 500 r2: Handle native-id download for HLS and SLC
  data_subscriber/download.py
Labels: bug, pcm.r01, needs triage, pcm.r02

#499 Issue 464: add SLC audit support to audit scripts
  geo/geo_util.py
  setup.py
  tools/README.md
  tools/cmr_audit.py
  tools/cmr_audit/__init__.py
  tools/cmr_audit/cmr_audit_hls.py
  tools/cmr_audit/cmr_audit_slc.py
  tools/cmr_audit/cmr_audit_utils.py
  tools/cmr_audit/cmr_client.py
  tools/cnm_check.py
  tools/hls_audit.py
  tools/slc_audit.py
Labels: enhancement, needs triage, pcm.r02

#508 Update HySDS to v5.0.0 beta.6 and AMIs
  cluster_provisioning/modules/common/variables.tf
  conf/sds/files/es_ilm_policy_mozart.json
  conf/sds/files/event_status.template
  conf/sds/files/job_status.template
  conf/sds/files/task_status.template
  conf/sds/files/test/purge_rs.sh
  conf/sds/files/worker_status.template
Labels: enhancement, pcm.r02
