Repository nasa/opera-sds-pcm, pull requests merged in 2024-03, with the labels that each got.

#745 Issue 737: utility for callling data subscriber for RTC
  cluster_provisioning/modules/common/mozart.tf
  data_subscriber/daac_data_subscriber.py
  data_subscriber/query.py
  data_subscriber/rtc/rtc_download_job_submitter.py
  data_subscriber/rtc/rtc_job_submitter.py
  data_subscriber/rtc/rtc_query.py
  setup.py
  tools/ops/README.md
  tools/ops/data_subscriber/__init__.py
  tools/ops/data_subscriber/data_subscriber_client.py
Labels: pcm.r03

#754 Issue 689: Add EC2 instance types for jobs with t3a.medium
  cluster_provisioning/modules/common/variables.tf
Labels: enhancement, pcm.r03

#752 Disp s1 integration test
  cluster_provisioning/run_opera_smoke_tests.sh
  cluster_provisioning/run_opera_unit_tests.sh
  data_subscriber/daac_data_subscriber.py
  docker/Dockerfile
  pytest.ini
  tests/data_subscriber/test_cslc_query.py
  tests/data_subscriber/test_daac_data_subscriber.py
  tests/data_subscriber/test_query.py
  tests/scenarios/cslc_query_test.py
Labels: pcm.r03

#758 DSWx-S1 PGE RC2.0 Integration
  cluster_provisioning/dev-e2e/variables.tf
  cluster_provisioning/dev-int/override.tf
  cluster_provisioning/dev/variables.tf
  cluster_provisioning/ebs-snapshot/variables.tf
  cluster_provisioning/modules/common/mozart.tf
  cluster_provisioning/modules/common/variables.tf
  conf/settings.yaml
  data_subscriber/rtc/mgrs_bursts_collection_db_client.py
  docker/hysds-io.json.SCIFLO_L2_CSLC_S1
  docker/hysds-io.json.SCIFLO_L2_CSLC_S1_STATIC
  docker/hysds-io.json.SCIFLO_L2_CSLC_S1_STATIC_hist
  docker/hysds-io.json.SCIFLO_L2_CSLC_S1_hist
  docker/hysds-io.json.SCIFLO_L2_RTC_S1
  docker/hysds-io.json.SCIFLO_L2_RTC_S1_STATIC
  docker/hysds-io.json.SCIFLO_L3_DISP_S1
  docker/hysds-io.json.SCIFLO_L3_DISP_S1_hist
  docker/hysds-io.json.SCIFLO_L3_DSWx_HLS
  docker/hysds-io.json.SCIFLO_L3_DSWx_S1
  docker/job-spec.json.SCIFLO_L2_CSLC_S1
  docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC
  docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC_hist
  docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist
  docker/job-spec.json.SCIFLO_L2_RTC_S1
  docker/job-spec.json.SCIFLO_L2_RTC_S1_STATIC
  docker/job-spec.json.SCIFLO_L3_DISP_S1
  docker/job-spec.json.SCIFLO_L3_DISP_S1_hist
  docker/job-spec.json.SCIFLO_L3_DSWx_HLS
  docker/job-spec.json.SCIFLO_L3_DSWx_S1
  opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml
  opera_chimera/opera_pge_job_submitter.py
  opera_chimera/precondition_functions.py
  tools/ops/README.md
  wrapper/opera_pge_wrapper.py
  wrapper/pge_functions.py
Labels: enhancement, needs triage, pcm.r03

#753 Issue 705: dswx-s1 trigger logic tests
  benchmark/test_benchmark.py
  cluster_provisioning/dev-e2e/main.tf
  data_subscriber/asf_rtc_download.py
  data_subscriber/daac_data_subscriber.py
  data_subscriber/query.py
  data_subscriber/rtc/evaluator.py
  data_subscriber/rtc/mgrs_bursts_collection_db_client.py
  data_subscriber/rtc/rtc_catalog.py
  data_subscriber/rtc/rtc_download_job_submitter.py
  integration/test_integration.py
  pip.conf
  regression/test_dswx_s1_edge_cases.py
  setup.py
  tests/opera_chimera/test_precondition_functions.py
  tools/ops/README.md
Labels: pcm.r03

#763 ES snapshot policy is now daily instead of hourly
  cluster_provisioning/modules/common/mozart.tf
Labels: enhancement, pcm.r03
