Repository nasa/opera-sds-pcm, pull requests merged in 2024-07, with the labels that each got.

#897 #896: CSLC download job now accepts --processing-mode as a parameter
  cluster_provisioning/modules/common/variables.tf
  data_subscriber/parser.py
  docker/hysds-io.json.cslc_download
  docker/job-spec.json.cslc_download
  docker/job-spec.json.cslc_download_hist
Labels: pcm.r03-dswx-s1

#894 Issue 886: address code review comments
  TESTING.md
  data_subscriber/rtc/evaluator.py
  tests/unit/data_subscriber/rtc/test_evaluator.py
Labels: enhancement, pcm.r03-dswx-s1

#910 Use c7i & m7i EC2 types for DSWx-S1
  cluster_provisioning/modules/common/variables.tf
Labels: enhancement, pcm.r03-dswx-s1

#899 Code resolution for issue-888: dswx-validator report auditing feature
  report/dswx-s1-validator/README.md
  report/dswx-s1-validator/dswx_s1_validator.py
Labels: enhancement, pcm.r03-dswx-s1

#917 Issue 888: dswx_s1 validator update
  report/dswx-s1-validator/README.md
  report/dswx-s1-validator/dswx_s1_validator.py
Labels: enhancement, pcm.r03-dswx-s1

#918 Fixed validation bug
  report/dswx-s1-validator/README.md
Labels: bug, pcm.r03-dswx-s1

#893 Data Subscriber Product Catalog Class Refactor
  data_subscriber/asf_cslc_download.py
  data_subscriber/asf_rtc_download.py
  data_subscriber/catalog.py
  data_subscriber/cslc/cslc_catalog.py
  data_subscriber/cslc/cslc_static_catalog.py
  data_subscriber/daac_data_subscriber.py
  data_subscriber/hls/hls_catalog.py
  data_subscriber/hls/hls_catalog_connection.py
  data_subscriber/hls/hls_query.py
  data_subscriber/hls_spatial/__init__.py
  data_subscriber/hls_spatial/hls_spatial_catalog.py
  data_subscriber/hls_spatial/hls_spatial_catalog_connection.py
  data_subscriber/query.py
  data_subscriber/rtc/evaluator.py
  data_subscriber/rtc/rtc_catalog.py
  data_subscriber/slc/slc_catalog.py
  data_subscriber/slc/slc_catalog_connection.py
  data_subscriber/slc/slc_query.py
  data_subscriber/slc_spatial/__init__.py
  data_subscriber/slc_spatial/slc_spatial_catalog.py
  data_subscriber/slc_spatial/slc_spatial_catalog_connection.py
  tests/data_subscriber/test_daac_data_subscriber.py
  tests/scenarios/cslc_query_test.py
  tests/unit/__init__.py
  tests/unit/conftest.py
  tests/unit/data_subscriber/test_catalog.py
Labels: enhancement, pcm.r01, pcm.r02, pcm.r03-dswx-s1, pcm.r03-disp-s1
